name: Build Android APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # خطوة سحرية لإنشاء ملف .env وحقن المفتاح السري داخله بأمان أثناء البناء
    - name: Inject Gemini API Key
      run: |
        echo "MAIN_API_KEY=${{ secrets.GEMINI_API_KEY }}" > .env
        echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> .env

    - name: Generate Correct Gradle Wrapper
      run: gradle wrapper

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Correct Gradle Version
      run: ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: my-gemini-app
        path: app/build/outputs/apk/debug/app-debug.apk
        
